export type KarachiZoneSeed = {
  name: string;
  areas?: string[];
};

const numbered = (prefix: string, first: number, last: number) =>
  Array.from(
    { length: last - first + 1 },
    (_, index) => `${prefix} ${first + index}`,
  );

const zones = (names: string[]): KarachiZoneSeed[] =>
  names.map((name) => ({ name }));

export const karachiZones: KarachiZoneSeed[] = [
  {
    name: "Gulshan-e-Iqbal",
    areas: [
      ...numbered("Block", 1, 12),
      "Block 13",
      "Block 13-D",
      "Block 13-D/1",
      "Block 13-D/2",
      "Block 13-D/3",
      ...numbered("Block", 14, 20),
    ],
  },
  { name: "Gulistan-e-Johar", areas: numbered("Block", 1, 22) },
  { name: "Gulzar-e-Hijri", areas: numbered("Sector", 1, 24) },
  {
    name: "North Nazimabad",
    areas: [
      "Block A",
      "Block B",
      "Block C",
      "Block D",
      "Block E",
      "Block F",
      "Block G",
      "Block H",
      "Block I",
      "Block J",
      "Block K",
      "Block L",
      "Block M",
      "Block N",
      "Block P",
      "Block Q",
      "Block R",
      "Block S",
      "Block T",
      "Block U",
      "Block V",
    ],
  },
  { name: "Nazimabad", areas: numbered("No.", 1, 12) },
  { name: "Federal B Area", areas: numbered("Block", 1, 20) },
  { name: "Liaquatabad", areas: numbered("No.", 1, 7) },
  {
    name: "New Karachi",
    areas: [
      "Sector 1",
      "Sector 2",
      "Sector 3",
      "Sector 4",
      "Sector 5",
      "Sector 5-D",
      "Sector 5-E",
      ...numbered("Sector", 6, 15),
      "Sector 11-A",
      "Sector 11-B",
      "Sector 11-C",
      "Sector 11-D",
    ],
  },
  { name: "PECHS", areas: numbered("Block", 1, 12) },
  { name: "Clifton", areas: numbered("Block", 1, 12) },
  {
    name: "DHA Phase 5",
    areas: [
      "Khayaban-e-Bukhari",
      "Khayaban-e-Shahbaz",
      "Khayaban-e-Ittehad",
      "Khayaban-e-Seher",
      "Khayaban-e-Jami",
      "Khayaban-e-Muhafiz",
      "Khayaban-e-Nishat",
      "Khayaban-e-Rahat",
      "Khayaban-e-Badar",
      "Khayaban-e-Hafiz",
    ],
  },
  {
    name: "DHA Phase 6",
    areas: [
      "Khayaban-e-Ittehad",
      "Khayaban-e-Shahbaz",
      "Khayaban-e-Seher",
      "Khayaban-e-Bukhari",
      "Commercial Area",
    ],
  },
  {
    name: "DHA Phase 7",
    areas: ["Khayaban-e-Tipu Sultan", "Khayaban-e-Hafiz", "Commercial Area"],
  },
  {
    name: "DHA Phase 8",
    areas: ["Khayaban-e-Shaheen", "Khayaban-e-Nishat", "Commercial Area"],
  },
  {
    name: "Korangi",
    areas: [...numbered("Sector", 30, 37), ...numbered("Sector", 41, 45)],
  },
  { name: "Landhi", areas: numbered("No.", 1, 12) },
  { name: "Shah Faisal Colony", areas: numbered("No.", 1, 7) },
  {
    name: "Orangi Town",
    areas: [
      ...numbered("Sector", 1, 10),
      "Sector 11",
      "Sector 11½",
      ...numbered("Sector", 12, 15),
    ],
  },
  { name: "Baldia Town", areas: numbered("Sector", 1, 8) },
  {
    name: "North Karachi",
    areas: [
      "Sector 1",
      "Sector 2",
      "Sector 3",
      "Sector 4",
      "Sector 5",
      "Sector 5-C",
      "Sector 5-D",
      "Sector 5-E",
      "Sector 7",
      "Sector 8",
      "Sector 9",
      "Sector 10",
      "Sector 11",
      "Sector 11-A",
      "Sector 11-B",
      "Sector 11-C",
      "Sector 11-D",
      "Sector 12",
      "Sector 13",
      "Sector 14",
    ],
  },
  { name: "Surjani Town", areas: numbered("Sector", 1, 18) },
  { name: "Gulshan-e-Maymar", areas: numbered("Sector", 1, 20) },
  ...zones([
    "NIPA",
    "Civic Centre",
    "Hasan Square",
    "Maskan Chowrangi",
    "Gulshan Chowrangi",
    "Aladin Park",
    "Safari Park",
    "National Stadium",
    "Pehlwan Goth",
    "Munawar Chowrangi",
    "Kamran Chowrangi",
    "Johar Mor",
    "Perfume Chowk",
    "KDA Chowrangi",
    "Safoora Chowrangi",
    "Continental Bakery",
    "University Road",
    "Ahsanabad",
    "Safoora Goth",
    "Gujro",
    "Dalmia",
    "Abul Hassan Isphahani Road",
    "Kausar Town",
    "Maymarabad",
    "Hyderi",
    "Sakhi Hassan",
    "Farooq-e-Azam",
    "Sir Syed Colony",
    "Siddiq-e-Akbar",
    "Buffer Zone",
    "Taimooria",
    "Al-Falah",
    "Pahar Ganj",
    "Mustafaabad",
    "Five Star Chowrangi",
    "Paposh Nagar",
    "Abbasi Shaheed",
    "Hadi Market",
    "Rizvia Society",
    "Firdous Colony",
    "Gulbahar",
    "Shafiq Mill Colony",
    "Samanabad",
    "Water Pump",
    "Naseerabad",
    "Yaseenabad",
    "Azizabad",
    "Karimabad",
    "Moosa Colony",
    "Sharifabad",
    "Bandhani Colony",
    "Ibn-e-Seena",
    "Commercial Area",
    "Dak Khana",
    "C-Area",
    "Super Market",
    "Mujahid Colony",
    "Shah Nawaz Bhutto Colony",
    "Gulshan-e-Saeed",
    "Khawaja Ajmeer Nagri",
    "Godhra",
    "Abu Zar Ghaffari",
    "Khamiso Goth",
    "Madina Colony",
    "Faisal Colony",
    "Hakim Ahsan",
    "Kailana",
    "Mustafa Colony",
    "Kala School",
    "Tariq Road",
    "Bahadurabad",
    "Nursery",
    "Kokan Society",
    "Shaheed-e-Millat Road",
    "Shahrah-e-Quaideen",
    "Dhoraji",
    "New Dhoraji",
    "Khalidabad",
    "Jamshed Quarters",
    "PIB Colony",
    "Soldier Bazaar",
    "Pakistan Quarters",
    "Jacob Lines",
    "Martin Quarters",
    "Clayton Quarters",
    "Essa Nagri",
    "Patel Para",
    "Ranchore Line",
    "Garden East",
    "Garden West",
    "Guru Mandir",
    "Lasbela",
    "Garden",
    "Nishtar Road",
    "Empress Market",
    "Preedy Street",
    "Regal Chowk",
    "Bohri Bazaar",
    "Zainab Market",
    "Rainbow Centre",
    "Abdullah Haroon Road",
    "Burns Road",
    "Pakistan Chowk",
    "Civil Lines",
    "Frere Town",
    "Cantt Station",
    "City Railway Colony",
    "Hijrat Colony",
    "Kharadar",
    "Mithadar",
    "Jodia Bazaar",
    "Sarafa Bazaar",
    "Old City Area",
    "Bhim Pura",
    "Ghanchi Para",
    "Hassan Lashkari Village",
    "Boat Basin",
    "Sea View",
    "Do Darya",
    "Teen Talwar",
    "Bilawal Chowrangi",
    "Zamzama",
    "Kehkashan",
    "DHA Phase 1",
    "DHA Phase 2",
    "DHA Phase 2 Extension",
    "DHA Phase 4",
    "DHA Phase 7 Extension",
    "Agra Taj Colony",
    "Bihar Colony",
    "Gulistan Colony",
    "Singo Lane",
    "Nawa Lane",
    "Kalakot",
    "Rexer Lane",
    "Ghulam Muhammad Lane",
    "Ragiwara",
    "Kalri",
    "Shah Baig Lane",
    "Darya Abad",
    "Hingorabad",
    "Khadda Memon Society",
    "Baghdadi",
    "Nayabad",
    "Jinnahabad",
    "Ghulam Shah Lane",
    "Moosa Lane",
    "Chakiwara",
    "Allama Iqbal Colony",
    "Bilal Colony",
    "Nasir Colony",
    "Silver Town",
    "Hundred Quarters",
    "Chakra Goth",
    "Zaman Town",
    "Hasrat Mohani Colony",
    "Bhatti Colony",
    "Qayyumabad",
    "Zia Colony",
    "Muzaffarabad",
    "Muslimabad",
    "Dawood Chowrangi",
    "Moinabad",
    "Sharafi Goth",
    "Bhutto Nagar",
    "Khawaja Ajmeer Colony",
    "Awami Colony",
    "Burmee Colony",
    "Sherabad",
    "Reta Plot",
    "Drigh Colony",
    "Rifah Aam Society",
    "Al-Falah Society",
    "Natha Khan Goth",
    "Kala Board",
    "Malir",
    "Malir City",
    "Malir Halt",
    "Malir 15",
    "Malir 6",
    "Model Colony",
    "Saudabad",
    "Khokhrapar",
    "Jafar-e-Tayyar",
    "Gharibabad",
    "Ghazi Brohi Goth",
    "Dawood Goth",
    "Khuldabad",
    "Future Colony",
    "Bithaiabad",
    "Bakhtawar Goth",
    "Mominabad",
    "Haryana Colony",
    "Hanifabad",
    "Mohammad Nagar",
    "Ghaziabad",
    "Chishti Nagar",
    "Iqbal Baloch Colony",
    "Gabol Colony",
    "Data Nagar",
    "Mujahidabad",
    "Baloch Goth",
    "Qasba Colony",
    "SITE Area",
    "Metroville",
    "Pak Colony",
    "Old Golimar",
    "Jahanabad",
    "Pathan Colony",
    "Frontier Colony",
    "Banaras Colony",
    "Islamia Colony",
    "Sher Shah",
    "Habib Bank Chowrangi",
    "SITE Chowrangi",
    "Gulshan-e-Ghazi",
    "Ittehad Town",
    "Islam Nagar",
    "Nai Abadi",
    "Saeedabad",
    "Muslim Mujahid Colony",
    "Muhajir Camp",
    "Rasheedabad",
    "Keamari",
    "Jackson Market",
    "Railway Colony",
    "Bhutta Village",
    "Sultanabad",
    "Machar Colony",
    "Baba Island",
    "Bhit Island",
    "Maripur",
    "Mauripur",
    "Hawkes Bay",
    "Manora",
    "KPT",
    "Gabo Pat",
    "Manghopir",
    "Pakhtunabad",
    "Pirabad",
    "Qaimkhani Colony",
    "Wangi Goth",
    "Mianwali Colony",
    "Khuda Ki Basti",
    "4K Chowrangi",
    "2 Minute Chowrangi",
    "Gadap",
    "Gaghar",
    "Pipri",
    "Songal",
    "Darsano Channo",
    "Yousuf Goth",
    "Tharoor",
    "Saleh Muhammad",
    "Murad Memon Goth",
    "Shah Mureed",
    "Ibrahim Hyderi",
    "Chowkandi",
    "Shah Latif",
    "Cattle Colony",
    "Majeed Colony",
    "Sher Pao Colony",
    "Chashma",
    "Rehri",
    "Ali Akbar Shah",
    "Bin Qasim",
    "Port Qasim",
    "Steel Town",
    "Gulshan-e-Hadeed",
    "Quaidabad",
    "Landhi Industrial Area",
    "Bhains Colony",
    "Shahrah-e-Faisal",
    "Karsaz",
    "Star Gate",
    "FTC",
    "Airport",
    "Bukhari Commercial",
    "Badar Commercial",
    "Nishat Commercial",
    "Ittehad Commercial",
    "Seher Commercial",
    "Aisha Manzil",
  ]),
];

export const normalizeLocationName = (name: string) =>
  name.replace(/\s+/g, " ").trim();

export const slugifyLocation = (name: string) =>
  normalizeLocationName(name)
    .toLowerCase()
    .replace(/½/g, "1-2")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
